syntax = "proto3";

// dashboard pb.dart 의 GrpcServiceName 과 일치시킴
package ai.swm.trudy.daq;

message void_ {}

message Sensor {
  string name = 1;
  enum HealthCheck {
    ENABLE = 0;
    UNABLE = 1;
  }
  optional HealthCheck ability = 2;
}

message Sensors {
  repeated string list = 1;
  string reason = 2;
}

message Connection {
  string name = 1;
  enum State {
    UNKNOWN = 0;
    CONNECTED = 1;
    DISCONNECTED = 2;
  }
  State state = 2;
}

message Connections {
  repeated Connection list = 1;
}

message Health {
  string name = 1;
  enum Status {
    UNKNOWN = 0;
    GOOD = 1;
    WARN = 2;
    BAAD = 3;
  }
  Status status = 2;
  string reason = 3;
}

message Healths {
  repeated Health list = 1;
}

message SensorSnapshot {
  string name = 1;
  string content_type = 2;
  bytes data = 3;
}

message SensorSnapshots {
  repeated SensorSnapshot list = 1;
}

message Acquisition {
  string name = 1;
  enum State {
    UNKNOWN = 0;
    ACQUIRING = 1;
    NOT_ACQUIRING = 2;
  }
  State state = 2;
  string reason = 3;
}

message Acquisitions {
  repeated Acquisition list = 1;
}

service Gateway {
  rpc ping(void_) returns (void_);

  rpc get_sensors(void_) returns (Sensors);

  rpc is_sensor_connected(Sensor) returns (Connection);
  rpc is_all_sensor_connected(void_) returns (Connections);

  rpc is_sensor_healthy(Sensor) returns (Health);
  rpc is_all_sensor_healthy(void_) returns (Healths);

  rpc get_sensor_snapshot(Sensor) returns (SensorSnapshot);
  rpc get_all_sensor_snapshot(void_) returns (SensorSnapshots);

  rpc is_sensor_acquiring(Sensor) returns (Acquisition);
  rpc is_all_sensor_acquiring(void_) returns (Acquisitions);

  rpc start_sensor_acquisition(Sensor) returns (Acquisition);
  rpc start_all_sensor_acquisition(void_) returns (Acquisitions);

  rpc stop_sensor_acquisition(Sensor) returns (Acquisition);
  rpc stop_all_sensor_acquisition(void_) returns (Acquisitions);
}
