# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import daq_service_pb2 as daq__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daq_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/protos.Service/ping',
                request_serializer=daq__service__pb2.void.SerializeToString,
                response_deserializer=daq__service__pb2.void.FromString,
                _registered_method=True)
        self.get_sensors = channel.unary_unary(
                '/protos.Service/get_sensors',
                request_serializer=daq__service__pb2.void.SerializeToString,
                response_deserializer=daq__service__pb2.Sensors.FromString,
                _registered_method=True)
        self.is_connected = channel.unary_unary(
                '/protos.Service/is_connected',
                request_serializer=daq__service__pb2.Sensor.SerializeToString,
                response_deserializer=daq__service__pb2.Connection.FromString,
                _registered_method=True)
        self.is_healthy = channel.unary_unary(
                '/protos.Service/is_healthy',
                request_serializer=daq__service__pb2.Sensor.SerializeToString,
                response_deserializer=daq__service__pb2.Health.FromString,
                _registered_method=True)
        self.get_snapshot = channel.unary_unary(
                '/protos.Service/get_snapshot',
                request_serializer=daq__service__pb2.Sensor.SerializeToString,
                response_deserializer=daq__service__pb2.SensorSnapshot.FromString,
                _registered_method=True)
        self.get_snapshots = channel.unary_unary(
                '/protos.Service/get_snapshots',
                request_serializer=daq__service__pb2.void.SerializeToString,
                response_deserializer=daq__service__pb2.SensorSnapshots.FromString,
                _registered_method=True)
        self.is_acquiring = channel.unary_unary(
                '/protos.Service/is_acquiring',
                request_serializer=daq__service__pb2.Sensor.SerializeToString,
                response_deserializer=daq__service__pb2.Acquisition.FromString,
                _registered_method=True)
        self.start_acquisition = channel.unary_unary(
                '/protos.Service/start_acquisition',
                request_serializer=daq__service__pb2.Sensor.SerializeToString,
                response_deserializer=daq__service__pb2.Acquisition.FromString,
                _registered_method=True)
        self.stop_acquisition = channel.unary_unary(
                '/protos.Service/stop_acquisition',
                request_serializer=daq__service__pb2.Sensor.SerializeToString,
                response_deserializer=daq__service__pb2.Acquisition.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_sensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_connected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_snapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_acquiring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_acquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_acquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=daq__service__pb2.void.FromString,
                    response_serializer=daq__service__pb2.void.SerializeToString,
            ),
            'get_sensors': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sensors,
                    request_deserializer=daq__service__pb2.void.FromString,
                    response_serializer=daq__service__pb2.Sensors.SerializeToString,
            ),
            'is_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_connected,
                    request_deserializer=daq__service__pb2.Sensor.FromString,
                    response_serializer=daq__service__pb2.Connection.SerializeToString,
            ),
            'is_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_healthy,
                    request_deserializer=daq__service__pb2.Sensor.FromString,
                    response_serializer=daq__service__pb2.Health.SerializeToString,
            ),
            'get_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_snapshot,
                    request_deserializer=daq__service__pb2.Sensor.FromString,
                    response_serializer=daq__service__pb2.SensorSnapshot.SerializeToString,
            ),
            'get_snapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.get_snapshots,
                    request_deserializer=daq__service__pb2.void.FromString,
                    response_serializer=daq__service__pb2.SensorSnapshots.SerializeToString,
            ),
            'is_acquiring': grpc.unary_unary_rpc_method_handler(
                    servicer.is_acquiring,
                    request_deserializer=daq__service__pb2.Sensor.FromString,
                    response_serializer=daq__service__pb2.Acquisition.SerializeToString,
            ),
            'start_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.start_acquisition,
                    request_deserializer=daq__service__pb2.Sensor.FromString,
                    response_serializer=daq__service__pb2.Acquisition.SerializeToString,
            ),
            'stop_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_acquisition,
                    request_deserializer=daq__service__pb2.Sensor.FromString,
                    response_serializer=daq__service__pb2.Acquisition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/ping',
            daq__service__pb2.void.SerializeToString,
            daq__service__pb2.void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_sensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/get_sensors',
            daq__service__pb2.void.SerializeToString,
            daq__service__pb2.Sensors.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/is_connected',
            daq__service__pb2.Sensor.SerializeToString,
            daq__service__pb2.Connection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/is_healthy',
            daq__service__pb2.Sensor.SerializeToString,
            daq__service__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/get_snapshot',
            daq__service__pb2.Sensor.SerializeToString,
            daq__service__pb2.SensorSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_snapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/get_snapshots',
            daq__service__pb2.void.SerializeToString,
            daq__service__pb2.SensorSnapshots.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_acquiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/is_acquiring',
            daq__service__pb2.Sensor.SerializeToString,
            daq__service__pb2.Acquisition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/start_acquisition',
            daq__service__pb2.Sensor.SerializeToString,
            daq__service__pb2.Acquisition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stop_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Service/stop_acquisition',
            daq__service__pb2.Sensor.SerializeToString,
            daq__service__pb2.Acquisition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
