# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daq_gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'daq_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import daq_service_pb2 as daq__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61q_gateway.proto\x12\x06protos\x1a\x11\x64\x61q_service.proto\"\x16\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x0b\x43onnections\x12 \n\x04list\x18\x01 \x03(\x0b\x32\x12.protos.Connection\"\'\n\x07Healths\x12\x1c\n\x04list\x18\x01 \x03(\x0b\x32\x0e.protos.Health\"1\n\x0c\x41\x63quisitions\x12!\n\x04list\x18\x01 \x03(\x0b\x32\x13.protos.Acquisition2\xc5\x06\n\x07Gateway\x12\"\n\x04ping\x12\x0c.protos.void\x1a\x0c.protos.void\x12,\n\x0bget_sensors\x12\x0c.protos.void\x1a\x0f.protos.Sensors\x12\x39\n\x13is_sensor_connected\x12\x0e.protos.Sensor\x1a\x12.protos.Connection\x12<\n\x17is_all_sensor_connected\x12\x0c.protos.void\x1a\x13.protos.Connections\x12\x33\n\x11is_sensor_healthy\x12\x0e.protos.Sensor\x1a\x0e.protos.Health\x12\x36\n\x15is_all_sensor_healthy\x12\x0c.protos.void\x1a\x0f.protos.Healths\x12=\n\x13get_sensor_snapshot\x12\x0e.protos.Sensor\x1a\x16.protos.SensorSnapshot\x12@\n\x17get_all_sensor_snapshot\x12\x0c.protos.void\x1a\x17.protos.SensorSnapshots\x12:\n\x13is_sensor_acquiring\x12\x0e.protos.Sensor\x1a\x13.protos.Acquisition\x12=\n\x17is_all_sensor_acquiring\x12\x0c.protos.void\x1a\x14.protos.Acquisitions\x12?\n\x18start_sensor_acquisition\x12\x0e.protos.Sensor\x1a\x13.protos.Acquisition\x12\x42\n\x1cstart_all_sensor_acquisition\x12\x0c.protos.void\x1a\x14.protos.Acquisitions\x12>\n\x17stop_sensor_acquisition\x12\x0e.protos.Sensor\x1a\x13.protos.Acquisition\x12\x41\n\x1bstop_all_sensor_acquisition\x12\x0c.protos.void\x1a\x14.protos.Acquisitionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daq_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICE']._serialized_start=48
  _globals['_DEVICE']._serialized_end=70
  _globals['_CONNECTIONS']._serialized_start=72
  _globals['_CONNECTIONS']._serialized_end=119
  _globals['_HEALTHS']._serialized_start=121
  _globals['_HEALTHS']._serialized_end=160
  _globals['_ACQUISITIONS']._serialized_start=162
  _globals['_ACQUISITIONS']._serialized_end=211
  _globals['_GATEWAY']._serialized_start=214
  _globals['_GATEWAY']._serialized_end=1051
# @@protoc_insertion_point(module_scope)
