# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import daq_gateway_pb2 as daq__gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daq_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/ping',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.void_.FromString,
                _registered_method=True)
        self.get_sensors = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/get_sensors',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.Sensors.FromString,
                _registered_method=True)
        self.is_sensor_connected = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/is_sensor_connected',
                request_serializer=daq__gateway__pb2.Sensor.SerializeToString,
                response_deserializer=daq__gateway__pb2.Connection.FromString,
                _registered_method=True)
        self.is_all_sensor_connected = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/is_all_sensor_connected',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.Connections.FromString,
                _registered_method=True)
        self.is_sensor_healthy = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/is_sensor_healthy',
                request_serializer=daq__gateway__pb2.Sensor.SerializeToString,
                response_deserializer=daq__gateway__pb2.Health.FromString,
                _registered_method=True)
        self.is_all_sensor_healthy = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/is_all_sensor_healthy',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.Healths.FromString,
                _registered_method=True)
        self.get_sensor_snapshot = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/get_sensor_snapshot',
                request_serializer=daq__gateway__pb2.Sensor.SerializeToString,
                response_deserializer=daq__gateway__pb2.SensorSnapshot.FromString,
                _registered_method=True)
        self.get_all_sensor_snapshot = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/get_all_sensor_snapshot',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.SensorSnapshots.FromString,
                _registered_method=True)
        self.is_sensor_acquiring = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/is_sensor_acquiring',
                request_serializer=daq__gateway__pb2.Sensor.SerializeToString,
                response_deserializer=daq__gateway__pb2.Acquisition.FromString,
                _registered_method=True)
        self.is_all_sensor_acquiring = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/is_all_sensor_acquiring',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.Acquisitions.FromString,
                _registered_method=True)
        self.start_sensor_acquisition = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/start_sensor_acquisition',
                request_serializer=daq__gateway__pb2.Sensor.SerializeToString,
                response_deserializer=daq__gateway__pb2.Acquisition.FromString,
                _registered_method=True)
        self.start_all_sensor_acquisition = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/start_all_sensor_acquisition',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.Acquisitions.FromString,
                _registered_method=True)
        self.stop_sensor_acquisition = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/stop_sensor_acquisition',
                request_serializer=daq__gateway__pb2.Sensor.SerializeToString,
                response_deserializer=daq__gateway__pb2.Acquisition.FromString,
                _registered_method=True)
        self.stop_all_sensor_acquisition = channel.unary_unary(
                '/ai.swm.trudy.daq.Gateway/stop_all_sensor_acquisition',
                request_serializer=daq__gateway__pb2.void_.SerializeToString,
                response_deserializer=daq__gateway__pb2.Acquisitions.FromString,
                _registered_method=True)


class GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_sensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_sensor_connected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_sensor_connected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_sensor_healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_sensor_healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_sensor_snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_sensor_snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_sensor_acquiring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_sensor_acquiring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_sensor_acquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_all_sensor_acquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_sensor_acquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_all_sensor_acquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.void_.SerializeToString,
            ),
            'get_sensors': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sensors,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.Sensors.SerializeToString,
            ),
            'is_sensor_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_sensor_connected,
                    request_deserializer=daq__gateway__pb2.Sensor.FromString,
                    response_serializer=daq__gateway__pb2.Connection.SerializeToString,
            ),
            'is_all_sensor_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_sensor_connected,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.Connections.SerializeToString,
            ),
            'is_sensor_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_sensor_healthy,
                    request_deserializer=daq__gateway__pb2.Sensor.FromString,
                    response_serializer=daq__gateway__pb2.Health.SerializeToString,
            ),
            'is_all_sensor_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_sensor_healthy,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.Healths.SerializeToString,
            ),
            'get_sensor_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sensor_snapshot,
                    request_deserializer=daq__gateway__pb2.Sensor.FromString,
                    response_serializer=daq__gateway__pb2.SensorSnapshot.SerializeToString,
            ),
            'get_all_sensor_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_sensor_snapshot,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.SensorSnapshots.SerializeToString,
            ),
            'is_sensor_acquiring': grpc.unary_unary_rpc_method_handler(
                    servicer.is_sensor_acquiring,
                    request_deserializer=daq__gateway__pb2.Sensor.FromString,
                    response_serializer=daq__gateway__pb2.Acquisition.SerializeToString,
            ),
            'is_all_sensor_acquiring': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_sensor_acquiring,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.Acquisitions.SerializeToString,
            ),
            'start_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.start_sensor_acquisition,
                    request_deserializer=daq__gateway__pb2.Sensor.FromString,
                    response_serializer=daq__gateway__pb2.Acquisition.SerializeToString,
            ),
            'start_all_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.start_all_sensor_acquisition,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.Acquisitions.SerializeToString,
            ),
            'stop_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_sensor_acquisition,
                    request_deserializer=daq__gateway__pb2.Sensor.FromString,
                    response_serializer=daq__gateway__pb2.Acquisition.SerializeToString,
            ),
            'stop_all_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_all_sensor_acquisition,
                    request_deserializer=daq__gateway__pb2.void_.FromString,
                    response_serializer=daq__gateway__pb2.Acquisitions.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.swm.trudy.daq.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.swm.trudy.daq.Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/ping',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.void_.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_sensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/get_sensors',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.Sensors.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_sensor_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/is_sensor_connected',
            daq__gateway__pb2.Sensor.SerializeToString,
            daq__gateway__pb2.Connection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_all_sensor_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/is_all_sensor_connected',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.Connections.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_sensor_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/is_sensor_healthy',
            daq__gateway__pb2.Sensor.SerializeToString,
            daq__gateway__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_all_sensor_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/is_all_sensor_healthy',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.Healths.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_sensor_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/get_sensor_snapshot',
            daq__gateway__pb2.Sensor.SerializeToString,
            daq__gateway__pb2.SensorSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_sensor_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/get_all_sensor_snapshot',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.SensorSnapshots.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_sensor_acquiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/is_sensor_acquiring',
            daq__gateway__pb2.Sensor.SerializeToString,
            daq__gateway__pb2.Acquisition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_all_sensor_acquiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/is_all_sensor_acquiring',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.Acquisitions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/start_sensor_acquisition',
            daq__gateway__pb2.Sensor.SerializeToString,
            daq__gateway__pb2.Acquisition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start_all_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/start_all_sensor_acquisition',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.Acquisitions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stop_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/stop_sensor_acquisition',
            daq__gateway__pb2.Sensor.SerializeToString,
            daq__gateway__pb2.Acquisition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stop_all_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.swm.trudy.daq.Gateway/stop_all_sensor_acquisition',
            daq__gateway__pb2.void_.SerializeToString,
            daq__gateway__pb2.Acquisitions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
